development:
  adapter: postgresql
  database: trivia_develpoment
  username: ryan
  host: localhost
  pool: 5
  timeout: 5000
  socket: /tmp/pgsql_socket

test: &test
  adapter: postgresql
  database: trivia_test
  username: ryan
  host: localhost
  pool: 5
  timeout: 5000
  socket: /tmp/pgsql_socket
  min_messages: WARNING

cucumber:
  <<: *test

production:
  adapter: postgresql
  database: trivia_develpoment
  username: ryan
  host: localhost
  pool: 5
  timeout: 5000
  socket: /tmp/pgsql_socket
